### ISSUE TITLE
Items displayed erroneously in search.

### ISSUE THREAD

**Issue by torque** [dokibox/dokibox#54]
If a library search is active when an item is added to a monitored directory, the Artist from that item will be displayed in the current search even if it doesn't match.

Here's a picture of the problem:

![example](https://cloud.githubusercontent.com/assets/949138/4778685/7cfea5ce-5bfb-11e4-9d63-2bbe9d1c73c0.png)

**Comment by mileswu** [comment]
reproduced

**Comment by mileswu** [comment]
Fixed in 38cebf7f9b07c76e4d3d4eeff0e20e65a40615e4
