### ISSUE TITLE
Quit on hide

### ISSUE THREAD

**Issue by torque** [dokibox/dokibox#77]
This is an old bug that I just figured out how to reliably reproduce. For later:

1. Play a song.
2. Seek in the song by clicking in the progress bar. 
3. Quickly press cmd+h to hide dokibox.
4. Dokibox will quit instead of hiding.

reproduces it 100% of the time for me.

**Comment by mileswu** [comment]
Confirmed.

**Comment by torque** [comment]
Update: will quit if cmd+h is pressed while hovering over the progress bar.

**Comment by mileswu** [comment]
The hover text is in its own window. For some reason if the application is hidden, when the hover window is closed, it thinks it was the last window and closes the entire application. Solution is not to use applicationShouldTerminateAfterLastWindowClosed.

**Comment by mileswu** [comment]
Issue #78 will also fix this one.
